### ISSUE TITLE
Document the MAX31865 reference resistor ratio

### ISSUE THREAD

**Issue by Kernald** [oddlama/embedded-devices#5]
The MAX31865 takes a reference resistor ratio as a `Rational32`, which I assume is the reference resistor value (e.g. 4.3k) against the RTD reference (e.g. 1k for a PT1000). My assumption might be incorrect though, as `read_temperature().await.unwrap().get::<degree_celsius>()` keeps yielding `-242.01003` in my instance as my room temperature, which is... a few hundred degrees off :-)

While I assume the issue is on my side, it would be nice having a bit more documentation around this device driver, just to make sure I'm using it correctly.

**Comment by oddlama** [comment]
Your assumption is absolutely correct, the ratio is `reference resistor value / nominal element resistance`. For modules out there that should be 4.3, so 43 over 10 in integers. I don't really like the rational interface right now, so maybe I can change that to be more intuitive in a later revision.

I only have a PT100 right now but a PT1000 is on its way from overseas, so I can properly test both in some weeks. I've moved the documentation from the private field to the initialization function now, thanks for noticing.

As to your problem: You will get -242.01003 °C when your device reports a measured resistance of zero. So this is likely an electrical issue. You can try to run an automatic fault detection with `detect_faults`. If that function returns an error you can read the fault register and look up the meaning in the datasheet.

**Comment by Kernald** [comment]
> Your assumption is absolutely correct, the ratio is `reference resistor value / nominal element resistance`. For modules out there that should be 4.3, so 43 over 10 in integers. I don't really like the rational interface right now, so maybe I can change that to be more intuitive in a later revision.

I understand why the ratio as it's how the device works, but I feel like accepting a number for the reference resistor and a second argument, either number or maybe an enum, for the probe nominal resistance, would make it a bit more obvious.

> I only have a PT100 right now but a PT1000 is on its way from overseas, so I can properly test both in some weeks. I've moved the documentation from the private field to the initialization function now, thanks for noticing.

Thanks for the quick fix!

> As to your problem: You will get -242.01003 °C when your device reports a measured resistance of zero. So this is likely an electrical issue. You can try to run an automatic fault detection with `detect_faults`. If that function returns an error you can read the fault register and look up the meaning in the datasheet.

Interestingly enough, using the Adafruit sample code for their library works as intended. I'll dig a bit more over the next few days and try and understand what's different between the two. The fault detection works as intended (i.e. if I unplug one of the four wires going to the RTD, I do get a fault), but it's unfortunately not reporting anything otherwise (at least in my instance), just the value of -242.01003C.

**Comment by oddlama** [comment]
> I understand why the ratio as it's how the device works, but I feel like accepting a number for the reference resistor and a second argument, either number or maybe an enum, for the probe nominal resistance, would make it a bit more obvious.

Yes that would probably be better.

> Interestingly enough, using the Adafruit sample code for their library works as intended. I'll dig a bit more over the next few days and try and understand what's different between the two. The fault detection works as intended (i.e. if I unplug one of the four wires going to the RTD, I do get a fault), but it's unfortunately not reporting anything otherwise (at least in my instance), just the value of -242.01003C.

It's absolutely possible that I made a mistake when introducing the codec implementations. Maybe there's an issue with raw data en/decoding. I'll also have a look at this later.

**Comment by Kernald** [comment]
> It's absolutely possible that I made a mistake when introducing the codec implementations. Maybe there's an issue with raw data en/decoding. I'll also have a look at this later.

From what I can tell, VBIAS never gets activated. Writing to the configuration registry always seems to be a no-op, and fetching the same registry after a write returns what looks like mostly 0s (from their interpretation). So I'm not surprised I'm only getting a virtually 0 temperature, and it makes me wonder if my SPI bus is working at all. I unfortunately don't have a logic analyzer at the moment... (Note, this is on an ESP32-S3 with esp-idf)

**Comment by Kernald** [comment]
As discussed on Matrix, this issue was two folds:
 - This device only supports SPI mode 1 or 3
 - The address issue fixed in 24084e3f555740fe1976508c8bb2c69aa5a1f2dd

Now working as intended :-)
